login_name = "//input[@id='signInName']"
auth0_intel_logo ="//img[@id='prompt-logo-center']"
auth0_login_error_message="//span[@id='error-element-password']"
# auth0_login_password_eye_button_hide_password = "//button[@class='ce7494284 ulp-button-icon c5bf19ed3 _button-icon']//span[@class='screen-reader-only password-toggle-label hide'][contains(text(),'Hide password')]"
auth0_login_password_eye_button_show_password = "//button[@type='button']"
auth0_login_validation_error_message = "//span[@id='error-element-password']"
auth0_forgot_password_button_through_login = "//*[contains(text(),'Forgot password?')]"
auth0_forgot_password_email_input = "//input[@id='email']"
auth0_forgot_password_page_continue_button= "//div[@class='c6d5cc3be']//button[contains(text(),'Continue')]"
auth0_forgot_password_page_back_to_idc_button = "//*[contains(text(),'Back to idc-client')]"
auth0_forgot_password_page_forgot_password_text = "//*[contains(text(),'Forgot Your Password?')]"
auth0_forgot_password_page_validation_error_invalid_email = "//span[@id='error-element-email']"
auth0_forgot_password_subheader_text="//*[contains(text(),'Enter your email address and we will send you instructions to reset your password.')]"
auth0_forgot_password_check_email_header_text = "//*[contains(text(),'Check Your Email')]"
auth0_forgot_password_email_logo="//div[@class='cbc698e37 cd2cfea10']"
auth0_login_welcome_text = "//*[contains(text(),'Welcome to Intel AI Cloud')]"
auth0_login_text = "//*[contains(text(),'Enter Email and password to log in')]"
auth0_login_email_input = "//input[@inputmode='email']"
auth0_login_password_input = "//input[@id='password']"
auth0_login_continue_button = "//div[@class='c00346576']//button[contains(text(),'Continue')]"